### ISSUE TITLE
Thread panicked at 'span does not point into this source file'

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview#105]
Typst Preview Version: 0.7.3
Typst Version: 0.7.0

```
["typst-book/contrib/typst/i18n.typ"]
[2023-08-27T13:29:51Z INFO  typst_ts_compiler::service::diag] \github-pages\docs\locale\zh_CN\format\book-meta.typ: compiling ...
thread '<unnamed>' panicked at 'span does not point into this source file', C:\Users\runneradmin\.cargo\git\checkouts\typst-15b90983aa0184a9\706d64f\crates\typst\src\lib.rs:102:1
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-08-27T13:29:52Z DEBUG typst_preview::actor::editor] EditorActor: received message from editor: UpdateMemoryFiles ["typst-book/contrib/typst/i18n.typ"]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src\actor\editor.rs:104:23
```

To reproduce:

1. edit the file https://github.com/Myriad-Dreamin/typst-book/blob/5ff6fa4e14c2dbc6563a5eb1e71addb1fac1d74a/contrib/typst/i18n.typ
  ```
  assert(flow_nodes.len() >= 1, message: "no id to translate")
  ```
  from `>=` to `>` and back to `>=`
1. randomly edit the text elements in file https://github.com/Myriad-Dreamin/typst-book/blob/5ff6fa4e14c2dbc6563a5eb1e71addb1fac1d74a/github-pages/docs/locale/zh_CN/format/book-meta.typ

**Comment by Enter-tainer** [comment]
This panic happens in typst itself, when processing doc to src jump request.

**Comment by Myriad-Dreamin** [comment]
Full stack trace:
```
[2023-08-29T03:38:06Z INFO  typst_ts_compiler::service::diag] \github-pages\docs\locale\zh_CN\format\book-meta.typ: compiling ...
thread '<unnamed>' panicked at 'span does not point into this source file', C:\Users\[hidden]\.cargo\git\checkouts\typst-15b90983aa0184a9\706d64f\crates\typst\src\lib.rs:102:1
stack backtrace:
   0:     0x7ff63deda19c - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff63df0244b - core::fmt::rt::Argument::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\rt.rs:138
   2:     0x7ff63df0244b - core::fmt::write
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\mod.rs:1094
   3:     0x7ff63ded4a6f - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\io\mod.rs:1714
   4:     0x7ff63ded9f4b - std::sys_common::backtrace::_print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff63ded9f4b - std::sys_common::backtrace::print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff63dedca1a - std::panicking::default_hook::closure$1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:269
   7:     0x7ff63dedc66f - std::panicking::default_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:288
   8:     0x7ff63dedd0ce - std::panicking::rust_panic_with_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:705
   9:     0x7ff63dedcfbd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:597
  10:     0x7ff63dedade9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff63dedccc0 - std::panicking::begin_panic_handler
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
  12:     0x7ff63df4eb35 - core::panicking::panic_fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
  13:     0x7ff63df4eaf2 - core::panicking::panic_display
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:150
  14:     0x7ff63df4eaf2 - core::panicking::panic_str
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:134
  15:     0x7ff63df4eaf2 - core::option::expect_failed
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\option.rs:1952
  16:     0x7ff63dcd0db2 - typst_syntax::source::Source::range::h772764d002cace7b
  17:     0x7ff63d2af6c8 - typst::World::range::hd4986400e0d5b667
  18:     0x7ff63dbab5b5 - comemo::cache::memoized::{{closure}}::h9f8a4a98177ad8ad
  19:     0x7ff63dba43ec - comemo::cache::memoized::{{closure}}::h9f8a4a98177ad8ad
  20:     0x7ff63db99de9 - comemo::cache::memoized::h75291853097e0632
  21:     0x7ff63db52fff - typst::eval::func::Func::call_vm::hd5941fd5c92d433d
  22:     0x7ff63d474a0d - typst::model::Vt::delayed::hba39e1e20d9d999b
  23:     0x7ff63d5f4839 - <typst_library::meta::context::LocateElem as typst::model::realize::Show>::show::hd8b31ecaa459a231
  24:     0x7ff63daed4ce - typst::model::realize::realize::h86036e8219255b5b
  25:     0x7ff63d5ea290 - typst_library::layout::define::h69e9238461ecef7f
  26:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  27:     0x7ff63d5ea4b0 - typst_library::layout::define::h69e9238461ecef7f
  28:     0x7ff63d5ea3c6 - typst_library::layout::define::h69e9238461ecef7f
  29:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  30:     0x7ff63d5ea4b0 - typst_library::layout::define::h69e9238461ecef7f
  31:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  32:     0x7ff63d5f27ab - typst_library::layout::realize_root::h25fd89773881bde4
  33:     0x7ff63d603398 - comemo::cache::memoized::h85b99e09fb39f8bc
  34:     0x7ff63d43aaed - <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::hbde5354b8ddd0d43
  35:     0x7ff63d3f2e50 - http::uri::scheme::Scheme::empty::h6e81c139f1cb2b86
  36:     0x7ff63db94d44 - comemo::cache::memoized::h139c00ab40234037
  37:     0x7ff63dadd6a4 - typst::model::typeset::h8e037222030d0fa1
  38:     0x7ff63dad5262 - typst::compile::h2a9993dd28be9b32
  39:     0x7ff63d2af8c5 - <C as typst_ts_compiler::service::DiagObserver>::with_compile_diag::h4859ad321f3293b0
  40:     0x7ff63d28d0eb - typst_preview::actor::typst::TypstActor::new::h88ebe99ffbaf6a36
  41:     0x7ff63d27d0e9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8e70adff2028f5ed
  42:     0x7ff63d27ef5f - core::fmt::Write::write_fmt::h4d1472d0999b2b2a
  43:     0x7ff63deeadac - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys\windows\thread.rs:57
  44:     0x7ff9725126ad - BaseThreadInitThunk
  45:     0x7ff9730eaa68 - RtlUserThreadStart

```
