### ISSUE TITLE
Images not appearing 

### ISSUE THREAD

**Issue by zmaril** [Enter-tainer/typst-preview#151]
Hello! Wonderful project, thank you very much for creating it! 

**Describe the bug**

I ran into a issue tonight with images not being rendered in the Typst Preview while rendering just fine with `typst compile`.

**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Follow the example from the docs for import images ([link](https://typst.app/docs/reference/visualize/image/ ). Put in a fake molecular picture to use as well. 
2. You should observe something like the following in the image preview
![Screenshot 2023-10-20 at 8 08 12 PM](https://github.com/Enter-tainer/typst-preview/assets/539927/cec7fe4b-3646-4537-b5a9-8e7e4e1ba19f)
3. Run `typst compile` on the same example file and observe that it pulls in the picture just fine. 
**Expected behavior**
The images in the preview are rendered the same way they are rendered when running `typst compile` on the CLI. 

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (1 wk ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.5.0
```

typst-preview extension version: `v0.7.3`

**Logs:**

typst-preview server log(Output Panel -> typst-preview):
```plain

```

typst-preview client log(Help -> Toggle Developer Tools -> Console):
```plain

```

**Additional context**

**Comment by Enter-tainer** [comment]
images should work. can you post the image which fails to render? so we can better diagnose this bug. you can also send that to my email lwzbill666@gmail.com if you dont want to publicly share it.

**Comment by Enter-tainer** [comment]
> Run typst compile on the same example file and observe that it **pulls** in the picture just fine.

are you using the url of the image? i dont know that can work in official cli

**Comment by Enter-tainer** [comment]
Can you elaborate? I can confirm that image works in many different document. Unless you provide a MWE, this cannot be resolved

**Comment by Enter-tainer** [comment]
@enivex also report when a new image is added, a reload is required. possibly related

**Comment by Enter-tainer** [comment]
reproduced.

```
[2023-10-27T14:31:29Z INFO  typst_ts_compiler::service::diag] \test.typ: Compilation failed after 100.8µs
error: file not found (searched at c:\Users\mgt\Desktop\proj\pkuthss-typst\images\1.png)
  ┌─ c:\Users\mgt\Desktop\proj\pkuthss-typst\test.typ:3:7
  │
3 │ #image("./images/1.png")
  │        ^^^^^^^^^^^^^^^^

thread 'typst-compiler' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\vfs\mod.rs:185:52
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:117
   3: enum2$<core::option::Option<ref$<alloc::sync::Arc<std::path::Path> > > >::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\option.rs:935
   4: typst_ts_compiler::vfs::Vfs<typst_ts_compiler::vfs::system::SystemAccessModel>::iter_dependencies_dyn
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\vfs\mod.rs:185
   5: typst_ts_compiler::world::impl$4::iter_dependencies
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\world.rs:255
   6: typst_ts_compiler::service::driver::impl$2::iter_dependencies<typst_ts_compiler::world::CompilerWorld<typst_ts_compiler::system::SystemCompilerFeat> >
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\service\driver.rs:102
   7: typst_ts_compiler::service::compile::CompileActor<typst_ts_compiler::service::export::CompileExporter<typst_ts_compiler::service::driver::CompileDriverImpl<typst_ts_compiler::world::CompilerWorld<typst_ts_compiler::system::SystemCompilerFeat> > > >::compi
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\service\compile.rs:236
   8: typst_ts_compiler::service::compile::impl$0::spawn::async_fn$0::async_block$3
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\service\compile.rs:210
   9: core::future::future::impl$1::poll<ref_mut$<enum2$<typst_ts_compiler::service::compile::impl$0::spawn::async_fn$0::async_block_env$3<typst_ts_compiler::service::export::CompileExporter<typst_ts_compiler::service::driver::CompileDriverImpl<typst_ts_compile
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\future\future.rs:125
  10: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0::closure$0
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:665
  11: tokio::runtime::coop::with_budget
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\coop.rs:107
  12: tokio::runtime::coop::budget
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\coop.rs:73
  13: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:665
  14: tokio::runtime::scheduler::current_thread::Context::enter<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure_env$0<core::pin::Pin<ref_mut$<enum2$<typst_ts_compiler::service::compile::
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:410
  15: tokio::runtime::scheduler::current_thread::impl$8::enter::closure$0
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:743
  16: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_env$0<tokio::runtime::scheduler::current_thread::impl$8:
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context\scoped.rs:40
  17: tokio::runtime::context::set_scheduler::closure$0
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context.rs:176
  18: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:270
  19: std::thread::local::LocalKey<tokio::runtime::context::Context>::with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:246
  20: tokio::runtime::context::set_scheduler<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2$<core::option::Option<tuple$<> > > >,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_env$0<tokio:
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context.rs:176
  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:743
  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on<core::pin::Pin<ref_mut$<enum2$<typst_ts_compiler::service::compile::impl$0::spawn::async_fn$0::async_block_env$3<typst_ts_compiler::service::export::CompileExporter<typst_ts_compiler::service:
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:652
  23: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::current_thread::impl$0::block_on::closure_env$0<enum2$<typst_ts_compiler::service::compile::impl$0::spawn::async_fn$0::async_block_env$3<typst_ts_compiler::service::export::Compile
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context\runtime.rs:65
  24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\current_thread\mod.rs:167
  25: tokio::runtime::runtime::Runtime::block_on<enum2$<typst_ts_compiler::service::compile::impl$0::spawn::async_fn$0::async_block_env$3<typst_ts_compiler::service::export::CompileExporter<typst_ts_compiler::service::driver::CompileDriverImpl<typst_ts_compiler
             at C:\Users\mgt\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\runtime.rs:347
  26: typst_ts_compiler::service::compile::ensure_single_thread::closure$0
             at C:\Users\mgt\.cargo\git\checkouts\typst.ts-bd03698c1f5efd74\004a0d3\compiler\src\service\compile.rs:522
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-10-27T14:31:29Z DEBUG typst_preview::actor::editor] EditorActor: received message from editor: UpdateMemoryFiles ["c:\\Users\\mgt\\Desktop\\proj\\pkuthss-typst\\test.typ"]
[2023-10-27T14:31:29Z DEBUG typst_preview::actor::typst] TypstActor: processing UPDATE memory files: ["c:\\Users\\mgt\\Desktop\\proj\\pkuthss-typst\\test.typ"]
[2023-10-27T14:31:29Z WARN  typst_ts_compiler::service::compile] CompileActor: send to mem_event error: channel closed

```

The compiler panics when the image is not found cc @Myriad-Dreamin
